### ISSUE TITLE
Is there autoencoders in this implementation？

### ISSUE THREAD

**Issue by CaiAnyu** [lpworld/PURS#1]
Hello, your paper is very impressive and helpful to me. I am not familiar with TensorFlow, but I find that the autoencoder is not used here, the latent space embeddings are learned directly in the training process. Is there autoencoders in this implementation？Or did I miss something？

**Comment by lpworld** [comment]
Hi CaiAnyu, thanks for your interest. The implementation we provided do not include the autoencoder module, as we wish to allow for more general use of the model (when no feature information is available). If you do have the explicit user and item features, you can of course implement the autoencoder framework and feed them into the recommendation model.

**Comment by CaiAnyu** [comment]
So did you use explicit features in the experiments on MovieLens and Yelp? Or you just use the ratings.csv?

**Comment by lpworld** [comment]
Hi CaiAnyu,

I use only ''ratings.csv'' for MovieLens and Yelp experiments for there are no explicit features available. I initialize and generate the user/item embeddings from their ids. Sorry for not making that clear in the paper.

Best Regards,
Pan

**Comment by CaiAnyu** [comment]
Got it. Thank you very much.
