### ISSUE TITLE
Question about Mean Shift Func

### ISSUE THREAD

**Issue by uvj1010** [lpworld/PURS#10]
Regarding Chapter 3.1 (Modeling of Unexpectedness) in the paper, historic behavior sequence (length = n) will be clustered into N user interest clusters, and for a new item, unexp is the weighted average distance between each cluster and
embedding of the new item.

But in the code (train.py - mean_shift) :

1. Each historical item is initialized as a center and iteratively shifted. The number of centers output is equal to the length of the historical sequence (n = N).

2. When calculating the distance between new item and clusters, all centers are averaged, which is not consistent with the "weighted average" and "multi user interest clusters" represented by formula 3.

**Comment by uvj1010** [comment]
> Regarding Chapter 3.1 (Modeling of Unexpectedness) in the paper, historic behavior sequence (length = n) will be clustered into N user interest clusters, and for a new item, unexp is the weighted average distance between each cluster and
> embedding of the new item.
> 
> But in the code (train.py - mean_shift) :
> 
> 1. Each historical item is initialized as a center and iteratively shifted. The number of centers output is equal to the length of the historical sequence (n = N).
> 2. When calculating the distance between new item and clusters, all centers are averaged, which is not consistent with the "weighted average" and "multi user interest clusters" represented by formula 3.

I think this implementation method is better in terms of calculation speed, and the dimension is fixed if the center is not merged, but does this calculation result meet the expectations of the paper?

**Comment by lpworld** [comment]
Thanks for your interest in our paper! Yes, if you check the output of the mean_shift component, you can find out that each item is clustered to its nearest center; (consider this toy example: [1,1,1,2,2,2,3,3,3,3] and the average would be 2.1 instead of 2) therefore, it is indeed a weighted average as we take into account the number of items in each center.

**Comment by uvj1010** [comment]
> Thanks for your interest in our paper! Yes, if you check the output of the mean_shift component, you can find out that each item is clustered to its nearest center; (consider this toy example: [1,1,1,2,2,2,3,3,3,3] and the average would be 2.1 instead of 2) therefore, it is indeed a weighted average as we take into account the number of items in each center.

Thanks for your explanation. For the example you given above, the result is indeed equal to a weighted sum. 

But because the close cluster centers may not be iterated to be exactly the same and the centers are not merged, the output of centers may be like this: [1, 0.998, 1.00013, ...] (I'm not sure what the real results will be, but I think it’s very possible). 
Then the result in the code will be different from the result which merge center first and then weighted average the distances. 

But I think it is still acceptable because the results are quite similar and the relative distance are basically correct and meaningful. Most importantly, I think this algorithm greatly improves the computational efficiency.  :-)
