### ISSUE TITLE
你好！请教您一些问题。

### ISSUE THREAD

**Issue by Aw-Ton** [lpworld/PURS#11]
问题1，阅读了论文，以及代码后，我对数据集中的time属性不是很理解，想问您，time具体是指什么，从公共数据集中（movielens）中构建训练数据时，time是指movielens数据集的那部分?
问题2，在代码中计算hit, cov, unexp时，每个指标都调用了一次模型，那可不可合并调用，只调用一次模型?
十分感谢，期待收到您的答复。

**Comment by lpworld** [comment]
你好！time就是指user-item interaction发生的时间，在movielens数据集里就是unix time。第二个问题，这个确实是可以指调用一次模型的，我们后续的evaluation部分已经做了优化，之后也会push到这里。

**Comment by Aw-Ton** [comment]
了解了，感谢你的答复
