### ISSUE TITLE
running  problems

### ISSUE THREAD

**Issue by WinnieZM** [lpworld/PURS#14]
“test_auc: 0.5240
Epoch 0 Global_step 100	Train_loss: 0.0434	Eval_AUC: 0.6877	Train_AUC: 0.7089
Epoch 0 Global_step 200	Train_loss: 0.0449	Eval_AUC: 0.6924	Train_AUC: 0.7349
Epoch 0 Global_step 300	Train_loss: 0.0413	Eval_AUC: 0.7068	Train_AUC: 0.7522
Epoch 0 DONE	Cost time: 55.93
Traceback (most recent call last):
  File "D:\GitHub_backup\PURS\train.py", line 166, in <module>
    hit = hit_rate(sess, model, test_set)
  File "D:\GitHub_backup\PURS\train.py", line 70, in hit_rate
    hit.append(sum([x[0] for x in arr_user])/len(arr_user))
ZeroDivisionError: division by zero
”
When I run the file, the above problem will occur, even if I modify the dataset. I have looked at the previous questions that everyone raised, but this situation did not occur. If it's convenient, could you please answer me? Thank you very much

**Comment by tiebreaker4869** [comment]
could you please tell me how do you fix this? I also encounter this problem.
