### ISSUE TITLE
Is the mean shift time-consuming?

### ISSUE THREAD

**Issue by CaiAnyu** [lpworld/PURS#3]
Sorry, It's me again. Is the mean shift time-consuming when training? In my reproduction, it seems too slow to train MovieLens-20M.

**Comment by lpworld** [comment]
Hi CaiAnyu,

Indeed, that is right. In fact, it is one of the two most time-consuming components in our model (the other one is the sequential modeling part. You can feel free to remove that part during your reproduction process (I have done that also for the ablation study). It might come with some performance loss, but it should be tolerable as long as you are not putting the model online.

Best Regards,
Pan

**Comment by CaiAnyu** [comment]
Thanks again.
