### ISSUE TITLE
您好，一点疑问

### ISSUE THREAD

**Issue by yandong667** [lpworld/PURS#6]
您好，PURS论文中提到的是利用历史消费物品(consumed items)的embedding去计算与新物品的意外性，但是看了您代码里头并没有对历史物品进行是否消费的过滤，不知道是否合理，还是我理解错了，这里就应该用全部的历史行为？
![image](https://user-images.githubusercontent.com/43993301/103874535-3d9ba500-510c-11eb-8d17-2395a1c8b73f.png)

**Comment by lpworld** [comment]
您好，这是一个很好的问题。你的理解没错，在一般的推荐场景里确实是应该只选择历史正样本来构建用户惊喜性。但是对于某些视频流、内容流推荐场景（比如youku）每次只推荐一个视频而且通常会进行自动播放，在这里正样本和负样本都会对用户之后的视频感知产生影响，所以在提供的代码里我们并没有对样本标签进行过滤。

**Comment by yandong667** [comment]
您好，所以您PURS论文中所用到的Movielens和Yelp的数据集中也是没有对历史样本中的负样本进行过滤吗？用的是正负样本相结合的上下文会话历史数据嘛？
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lpworld/PURS"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月8日(星期五) 上午9:07
收件人:&nbsp;"lpworld/PURS"<PURS@noreply.github.com&gt;;
抄送:&nbsp;"风还在发端"<775301251@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lpworld/PURS] 您好，一点疑问 (#6)





 
您好，这是一个很好的问题。你的理解没错，在一般的推荐场景里确实是应该只选择历史正样本来构建用户惊喜性。但是对于某些视频流、内容流推荐场景（比如youku）每次只推荐一个视频而且通常会进行自动播放，在这里正样本和负样本都会对用户之后的视频感知产生影响，所以在提供的代码里我们并没有对样本标签进行过滤。

**Comment by lpworld** [comment]
是的，之后我们也会考虑只选择正样本去构建惊喜推荐模型。在这篇文章里为了和视频流推荐场景一致，做了简化处理。

**Comment by yandong667** [comment]
明白啦，谢谢您的回复，您与您团队的贡献让我们钦佩不已。再次感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lpworld/PURS"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月8日(星期五) 中午11:28
收件人:&nbsp;"lpworld/PURS"<PURS@noreply.github.com&gt;;
抄送:&nbsp;"风还在发端"<775301251@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lpworld/PURS] 您好，一点疑问 (#6)





 
是的，之后我们也会考虑只选择正样本去构建惊喜推荐模型。在这篇文章里为了和视频流推荐场景一致，做了简化处理。
