### ISSUE TITLE
Meaning of utility function and r_ui

### ISSUE THREAD

**Issue by fenneccat** [lpworld/PURS#8]
As I asked you on [issue](https://github.com/lpworld/PURS/issues/7), 
I thought there are two different models: Base, and Unexpected.
However, it seems they are jointly trained with one standard, click-or-nonclick labels.
Since they are trained jointly with the same task, It seems it's hard to say `r_ui` is CTR (or click-or-nonclick) and `Unexp_Factor_ui` is only considering unexpectedness.
As I understood, one large model contains two separated parallel parts, and they are somehow cooperating to predict click-or-nonclick value. Did I understand correctly? or Can you explain how CTR and unexpectedness parts can clearly do their works respectively?

**Comment by lpworld** [comment]
Well, there is only one model, which contains two "components", one for the relevance objective and the other for the unexpectedness objective. The idea is that r_ui is the production system in the company which aims for predicting click-or-nonclick, therefore we refer to it as the CTR prediction. The unexpectedness is what we add into the model as an additional objective that jointly produces the final recommendations.

**Comment by fenneccat** [comment]
Thank you for reply! So, this model has two components and these two components are sharing one objective function but the idea of each component is came from a different motivation: predicting click-or-nonclick and unexpectedness. Is that correct? What I'm confusing is after training the model, does one component can work as its original purpose or not. For example, after training the model with loss function with r_ui and unexpectedness, if I detach only CTR component and give item, user, history inputs, does CTR component can work for predicting click or non-click info as we expected? and does detached unexpectedness part can predict user's unexpectedness factor for a certain item even though two components are separated after training?

**Comment by lpworld** [comment]
Yes, you can detach each component and that is exactly the beauty of this hybrid utility function design (which allows you to add/remove any recommendation objectives). The CTR component has already been used for click prediction in the company serving for the production system, and the unexpectedness component could predict the unexpectedness value as well, as suggested in the prior literature.

**Comment by fenneccat** [comment]
I have last question!

To use this model as a recommender system, did you put user, history, and all possible items to model and predict scores for each item and rank the item according to predicted score? Is this model used as a ranking model when serving?

**Comment by lpworld** [comment]
Yes, indeed we compute the utility score for all candidate items and rank them accordingly. (though during the serving stage it will also be combined with other business strategies from the product team to produce the final recommendations)
